INSERT INTO "LOGIN" (ID, USERNAME, PASSWORD) VALUES (1, 'Alice', 'Password123!');
INSERT INTO "LOGIN" (ID, USERNAME, PASSWORD) VALUES (2, 'Bob', 'Qwerty123!');
INSERT INTO "LOGIN" (ID, USERNAME, PASSWORD) VALUES (3, 'Charlie', 'Test1234!');